Sprint5
Ashutosh-Tigga-NucleusTeq/blog-portal-backend pull request #5
Opened 2023-10-01 14:52 UTC by Ashutosh-Tigga-NucleusTeq

2023-10-01 14:58 UTC, Abhishek-Hasda-nucleusteq commented on src/main/java/com/blog/portal/controller/CommentPostController.java
> +	private CommentPostService commentPostService;
follow the proper indentation.

2023-10-01 15:01 UTC, Abhishek-Hasda-nucleusteq commented on src/main/java/com/blog/portal/controller/BlogPostController.java
> +	private Logger logger = LogManager.getLogger(BlogPostController.class);
make it final and the variable should be in capital letter. LOGGER

2023-10-01 16:00 UTC, Abhishek-Hasda-nucleusteq requested changes

2023-10-02 12:07 UTC, Ashutosh-Tigga-NucleusTeq commented on src/main/java/com/blog/portal/serviceimpl/BlogPostServiceImpl.java
> +		user.setPassword(null);
i am setting null in password bcz it's i don't wanna reveal password to cliend bcz i am sending these data to client side this is not to save data in database

2023-10-05 07:31 UTC, Krishna-NucleusTeq requested changes

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/requestPayload/AuthenticateUserInDto.java
> +	/**
UserInDTO

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/serviceimpl/BlogServiceImpl.java
> +		}
what  if fetchedPost will empty?

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/serviceimpl/BlogServiceImpl.java
> +					inDto.getTechnologyCategory());
same as above

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/services/CommentService.java
> +
method name should be postComment

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/services/ReactionService.java
> +	ReactionOnBlogOutDto doReactOnBlog(ReactOnBlogInDto inDto);
BlogActivity

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/services/UserService.java
> +
UserOutDTO

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/BlogConst.java
> +	/**
Constants

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/BlogConst.java
> +}
POST_ID

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/ExceptionMessage.java
> +}
message should be Unauthorized user

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/RequestMappingConst.java
> +	/**
RestPathConstants

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/ResponseMessage.java
> +	/**
class should be final

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/ExceptionMessage.java
> +	/**
ErrorConstants

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/main/java/com/blog/portal/util/UserConst.java
Keep all the constants in one file, error messages in ErrorConstants, and url should be in restpathConstants

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/test/java/com/blog/portal/serviceimpl/UserServiceImplTest.java
> +    public void testCreateUser_UserAlreadyExists() {
testUserAlreadyExists

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/test/java/com/blog/portal/serviceimpl/UserServiceImplTest.java
> +        AuthenticateUserInDto authDto = new AuthenticateUserInDto();
testUserAuthenticatedSuccessfully

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/test/java/com/blog/portal/serviceimpl/UserServiceImplTest.java
> +        assertEquals(authDto.getEmail(), outDto.getEmail());
no need to check notNull, check whole object. expected and actual

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/test/java/com/blog/portal/serviceimpl/UserServiceImplTest.java
> +    }
no need to check notNull, check whole object. expected and actual

2023-10-05 07:31 UTC, Krishna-NucleusTeq commented on src/test/java/com/blog/portal/serviceimpl/ReactionServiceImplTest.java
> +        assertFalse(blog.getDisLikedBy().contains("userId"));
no need to check notNull and fields individually, check whole object. expected and actual

2023-10-05 10:34 UTC, Ashutosh-Tigga-NucleusTeq commented on src/main/java/com/blog/portal/repository/BlogRepository.java
> +
It is for filtering Blog by mentioned  criteria it's like custom query

2023-10-09 04:24 UTC, merged